BLOCK_MERGE_SEMVER_CONTEXT = "Semver label"
BLOCK_MERGE_VERIFY_CONTEXT = "Verified label"

LABEL_VERIFIED = "Verified"
LABEL_APPROVE = "Approve"
NEEDS_MAINTAINERS_APPROVE = "Needs Maintainers Approve"

LABEL_SEMVER_PREFIX = "Semver"
LABELS_SEMVER_MAJOR = [
    f"{LABEL_SEMVER_PREFIX}/Major",
    f"{LABEL_SEMVER_PREFIX}/Breaking-Change",
]
LABELS_SEMVER_MINOR = [
    f"{LABEL_SEMVER_PREFIX}/Minor",
    f"{LABEL_SEMVER_PREFIX}/Non-Breaking-Feature",
]
LABELS_SEMVER_PATCH = [
    f"{LABEL_SEMVER_PREFIX}/Patch",
    f"{LABEL_SEMVER_PREFIX}/Non-Breaking-Fix",
]
